<?php

namespace AppBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserRaul()
    {
        $qb = $this->getEntityManager()->createQueryBuilder()
            ->select('u')
            ->from('AppBundle:User', 'u')
            ->where('u.username = :username')
            ->setParameter('username', 'pepe')
            ->getQuery();
        return $qb->getResult();

    }
}
