# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
            AppBundle\Entity\User:
                algorithm: bcrypt
    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
            our_db_provider:
                entity:
                    class: AppBundle:User
                    property: email

    firewalls:
             dev:
                 pattern: ^/(_(profiler|wdt)|css|images|js)/
                 security: false

             main:
                 anonymous: ~
                 form_login:
                     login_path: login
                     check_path: login
                     default_target_path: login
                 logout:
                     path: /logout
                     target: /login

    access_control:
            - { path: ^/registro, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
            - { path: ^/, roles: ROLE_USER }